In [1]:
import pandas as pd

In [2]:
import sqlalchemy as sly
import psycopg2
engine = sly.create_engine('postgresql+psycopg2://postgres:admin@localhost:5432/postgres')

In [2]:
dataFrame=pd.read_csv("dataset_olympics.csv")

In [16]:
print( type(dataFrame)  )

<class 'pandas.core.frame.DataFrame'>

In [3]:
def simpleCleaning(fileDerectory):
    # data=pd.read_csv(fileDerectory,skiprows=1)
    data=pd.read_csv(fileDerectory)
    data.drop_duplicates(inplace=True)
    data.fillna("no value",inplace=True)
    return data

In [12]:
simpleCleaning("dataset_olympics.csv")

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,no value
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,no value
2,3,Gunnar Nielsen Aaby,M,24.0,no value,no value,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,no value
3,4,Edgar Lindenau Aabye,M,34.0,no value,no value,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,no value
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,35656,Stuart Fitzsimmons,M,19.0,no value,no value,Great Britain,GBR,1976 Winter,1976,Winter,Innsbruck,Alpine Skiing,Alpine Skiing Men's Giant Slalom,no value
69996,35656,Stuart Fitzsimmons,M,19.0,no value,no value,Great Britain,GBR,1976 Winter,1976,Winter,Innsbruck,Alpine Skiing,Alpine Skiing Men's Slalom,no value
69997,35657,"David Thomas ""Dave"" Fitzsimons",M,26.0,170.0,65.0,Australia,AUS,1976 Summer,1976,Summer,Montreal,Athletics,"Athletics Men's 10,000 metres",no value
69998,35657,"David Thomas ""Dave"" Fitzsimons",M,30.0,170.0,65.0,Australia,AUS,1980 Summer,1980,Summer,Moskva,Athletics,"Athletics Men's 5,000 metres",no value
69999,35658,Marek Fiurek,M,23.0,180.0,68.0,Czech Republic,CZE,1998 Winter,1998,Winter,Nagano,Nordic Combined,Nordic Combined Men's Team,no value

In [4]:
from math import ceil, floor

def devide_the_data(csv_porcentage,json_porcenntage,db_porcentage,lien_fichier,nom_csv_stocker,nom_json_stocker,nom_db_crier):
    handered_porcentage=csv_porcentage+json_porcenntage+db_porcentage
    if handered_porcentage>100 or handered_porcentage<100:
        print("la somme des pourcentage ne doit pas deppasser ou etre moi de 100 !")
    elif(type(lien_fichier)== str):
        df=simpleCleaning(lien_fichier)
        df_shuffled=df.sample(frac=1).reset_index(drop=True)
        print("shuffled",df_shuffled.head())
        total_lignes=len(df)
        csv_lignes=ceil((total_lignes*csv_porcentage)/100)
        print("csv_lignes :",csv_lignes)
        json_lignes=ceil((total_lignes*json_porcenntage)/100)
        print("json_lignes :",json_lignes)
        db_lignes=ceil((total_lignes*db_porcentage)/100)
        print("db_lignes :",db_lignes)
        all_ligns=csv_lignes+db_lignes+csv_lignes
        rest=total_lignes-all_ligns
        if rest != 0:
            csv_lignes=csv_lignes+rest
        
        print(csv_lignes)
        
        df_csv=df_shuffled.iloc[0:csv_lignes].to_csv(f"{nom_csv_stocker}.csv",index=False,header=False)
        df_json=df_shuffled.iloc[csv_lignes:(csv_lignes+json_lignes)].to_json(f"{nom_json_stocker}.json")
        df_db=df_shuffled.iloc[(csv_lignes+json_lignes):len(df_shuffled)].to_sql(f"{nom_db_crier}",engine, if_exists='replace',index=False)
        print("done!")
    else:
        print("something is not right")

In [6]:
# devide_the_data(csv_porcentage,json_porcenntage,db_porcentage,data)
# devide_the_data(20,20,60,"dataset_olympics.csv")
# devide_the_data(csv_porcentage,json_porcenntage,db_porcentage,lien_fichier,nom_csv_stocker,nom_json_stocker,nom_db_crier)
var_prcentage_csv=int(float(input("porcentage de csv : ")))
var_prcentage_json=int(float(input("porcentage de json : ")))
var_prcentage_db=int(float(input("porcentage de db : ")))
var_lien_deviser=input("lien vers le fichier CSV a deviser: ")
var_nom_csv_stocker=input("nom de fichier CSV a stocker: ")
var_prcentage_json_stocker=input("nom de fichier json a stocker: ")
var_prcentage_nom_db=input("nom de fichier database: ")


devide_the_data(var_prcentage_csv,var_prcentage_json,var_prcentage_db,var_lien_deviser,var_nom_csv_stocker,var_prcentage_json_stocker,var_prcentage_nom_db)

shuffled       ID                                   Name Sex   Age Height Weight  \
0  14312  Svetlana Sergeyevna Boyarkina-Zhurova   F  30.0  176.0   64.0
1  11929                          Erik Bjornsen   M  22.0  185.0   84.0
2   5236                        Haukur Arnrsson   M  26.0  175.0   70.0
3  29931         Kristopher Bruce "Kris" Draper   M  34.0  178.0   86.0
4  33013                        adan Derya Erke   F  16.0  163.0   59.0

            Team  NOC        Games  Year  Season            City  \
0         Russia  RUS  2002 Winter  2002  Winter  Salt Lake City
1  United States  USA  2014 Winter  2014  Winter           Sochi
2        Iceland  ISL  1998 Winter  1998  Winter          Nagano
3         Canada  CAN  2006 Winter  2006  Winter          Torino
4         Turkey  TUR  2000 Summer  2000  Summer          Sydney

                  Sport                                              Event  \
0         Speed Skating                 Speed Skating Women's 1,000 metres
1  Cross Country Skiing  Cross Country Skiing Men's 4 x 10 kilometres R...
2         Alpine Skiing                   Alpine Skiing Men's Giant Slalom
3            Ice Hockey                        Ice Hockey Men's Ice Hockey
4              Swimming             Swimming Women's 100 metres Backstroke

      Medal
0  no value
1  no value
2  no value
3  no value
4  no value
csv_lignes : 27151
json_lignes : 28543
db_lignes : 13924
28542
done!